//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFormula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemFormula()
        {
            this.MdItems = new HashSet<MdItem>();
        }
    
        public System.Guid Id { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> Cement { get; set; }
        public Nullable<double> Stone { get; set; }
        public Nullable<double> Sand { get; set; }
        public Nullable<double> Admixture { get; set; }
        public Nullable<double> Water { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MdItem> MdItems { get; set; }
    }
}
