//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MdItem()
        {
            this.ScaleBills = new HashSet<ScaleBill>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string UnitCode { get; set; }
        public string TypeCode { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> ItemFormula_Id { get; set; }
        public string SyncCode { get; set; }
    
        public virtual ItemFormula ItemFormula { get; set; }
        public virtual MdItemType MdItemType { get; set; }
        public virtual MdUnit MdUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaleBill> ScaleBills { get; set; }
    }
}
