//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScaleImage
    {
        public System.Guid Id { get; set; }
        public string ScaleBillCode { get; set; }
        public System.Guid AttachmentId { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncLog { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual ScaleBill ScaleBill { get; set; }
    }
}
