//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountGroupFunction
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public Nullable<bool> F_Add { get; set; }
        public Nullable<bool> F_Edit { get; set; }
        public Nullable<bool> F_Del { get; set; }
        public Nullable<bool> F_View { get; set; }
        public Nullable<bool> F_Print { get; set; }
        public Nullable<bool> F_Other { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    }
}
