//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public string ComId { get; set; }
        public string ComManager { get; set; }
        public string ComName { get; set; }
        public string ComAddress { get; set; }
        public string ComPhone { get; set; }
        public string ComFax { get; set; }
        public string ComEmail { get; set; }
        public string ComTax { get; set; }
        public string ComWebsite { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    }
}
