//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallToTrough
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string DeliveryCode { get; set; }
        public string Vehicle { get; set; }
        public Nullable<decimal> SumNumber { get; set; }
        public string Machine { get; set; }
        public Nullable<int> IndexTrough { get; set; }
        public int CountTry { get; set; }
        public int CountReindex { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string CallLog { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
    }
}
