//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevice
    {
        public int Id { get; set; }
        public string CodeParent { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> OperID { get; set; }
        public Nullable<int> DoorOrAuxoutID { get; set; }
        public Nullable<int> OutputAddrType { get; set; }
        public Nullable<int> DoorAction { get; set; }
        public Nullable<int> InputPort { get; set; }
        public Nullable<int> OutputPort { get; set; }
        public string Ipaddress { get; set; }
        public string Port { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    }
}
