//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weightman
    {
        public int Id { get; set; }
        public decimal Ticketnum { get; set; }
        public string Trantype { get; set; }
        public string Truckno { get; set; }
        public System.DateTime Date_in { get; set; }
        public Nullable<System.TimeSpan> time_in { get; set; }
        public Nullable<System.DateTime> Date_out { get; set; }
        public Nullable<System.TimeSpan> time_out { get; set; }
        public string Custcode { get; set; }
        public string Custname { get; set; }
        public string Prodcode { get; set; }
        public string Prodname { get; set; }
        public decimal Firstweight { get; set; }
        public Nullable<decimal> Secondweight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string mauhd { get; set; }
        public string Docnum { get; set; }
        public string sohd { get; set; }
        public Nullable<decimal> Netweight2 { get; set; }
        public System.DateTime Note { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public Nullable<double> vat { get; set; }
        public Nullable<decimal> tienvat { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string sp { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> Netweight { get; set; }
        public string ScaleBillCode { get; set; }
    }
}
