//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XHTD_Entities : DbContext
    {
        public XHTD_Entities()
            : base("name=XHTD_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MdArea> MdAreas { get; set; }
        public virtual DbSet<MdDevice> MdDevices { get; set; }
        public virtual DbSet<MdDeviceGroup> MdDeviceGroups { get; set; }
        public virtual DbSet<MdDeviceType> MdDeviceTypes { get; set; }
        public virtual DbSet<MdItem> MdItems { get; set; }
        public virtual DbSet<MdItemType> MdItemTypes { get; set; }
        public virtual DbSet<MdPartner> MdPartners { get; set; }
        public virtual DbSet<MdRfid> MdRfids { get; set; }
        public virtual DbSet<MdUnit> MdUnits { get; set; }
        public virtual DbSet<MdVehicle> MdVehicles { get; set; }
        public virtual DbSet<MdVehicleType> MdVehicleTypes { get; set; }
        public virtual DbSet<ScaleBill> ScaleBills { get; set; }
    }
}
